#import <CoreText/CoreText.h>

CF_IMPLICIT_BRIDGING_ENABLED
CF_EXTERN_C_BEGIN
CF_ASSUME_NONNULL_BEGIN

CT_EXPORT const CFStringRef kCTFontUIFontDesignTrait;
CT_EXPORT const CFStringRef kCTFontUIFontDesignMonospaced;
CT_EXPORT const CFStringRef kCTFontUIFontDesignDefault;
CT_EXPORT const CFStringRef kCTFontUIFontDesignRounded;
CT_EXPORT const CFStringRef kCTFontUIFontDesignSerif;

CT_EXPORT const CFStringRef kCTUIFontTextStyleTitle0;
CT_EXPORT const CFStringRef kCTUIFontTextStyleTitle1;
CT_EXPORT const CFStringRef kCTUIFontTextStyleTitle2;
CT_EXPORT const CFStringRef kCTUIFontTextStyleTitle3;
CT_EXPORT const CFStringRef kCTUIFontTextStyleHeadline;
CT_EXPORT const CFStringRef kCTUIFontTextStyleSubhead;
CT_EXPORT const CFStringRef kCTUIFontTextStyleBody;
CT_EXPORT const CFStringRef kCTUIFontTextStyleCallout;
CT_EXPORT const CFStringRef kCTUIFontTextStyleFootnote;
CT_EXPORT const CFStringRef kCTUIFontTextStyleCaption1;
CT_EXPORT const CFStringRef kCTUIFontTextStyleCaption2;
CT_EXPORT const CFStringRef kCTUIFontTextStyleExtraLargeTitle;
CT_EXPORT const CFStringRef kCTUIFontTextStyleExtraLargeTitle2;

CT_EXPORT const CFStringRef kCTFontContentSizeCategoryXS;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryS;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryM;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryXL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryXXL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryXXXL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryAccessibilityM;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryAccessibilityL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryAccessibilityXL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryAccessibilityXXL;
CT_EXPORT const CFStringRef kCTFontContentSizeCategoryAccessibilityXXXL;

CT_EXPORT const CFStringRef kCTFontLegibilityWeightAttribute;
CT_EXPORT const CFStringRef kCTFontTargetEnvironmentAttribute;

typedef CF_ENUM(NSInteger, CTFontLegibilityWeight) {
    CTFontLegibilityWeightRegular = 0,
    CTFontLegibilityWeightBold = 1
};

typedef CF_ENUM(uint32_t, CTFontTargetEnvironment) {
    CTFontTargetEnvironmentUnknown3 = 3
};

CF_ASSUME_NONNULL_END
CF_EXTERN_C_END
CF_IMPLICIT_BRIDGING_DISABLED
