#import <RealitySystemSupport/Defines.h>
#import <CoreRE/CoreRE.h>

NS_ASSUME_NONNULL_BEGIN

RCP_EXTERN REComponentClassPtr RCPInputTargetComponentGetCustomComponentType(void);
RCP_EXTERN void RCPInputTargetComponentSetTargetProperties(REComponent, RCPInputTargetComponentTargetProperties);
RCP_EXTERN RCPInputTargetComponentTargetProperties RCPInputTargetComponentGetTargetProperties(REComponent);

NS_ASSUME_NONNULL_END
