#import <CoreRE/Defines.h>
#import <Metal/Metal.h>

NS_ASSUME_NONNULL_BEGIN

RE_EXTERN REComponentClassPtr REMaterialParameterBlockArrayComponentGetComponentType(void) NS_SWIFT_NAME(getter:Component.ClassPtr.materialParameterBlockArray());
RE_EXTERN NSInteger REMaterialParameterBlockArrayComponentSize(REComponent) NS_SWIFT_NAME(getter:Component.materialParameterBlockArray_size(self:));
RE_EXTERN void REMaterialParameterBlockArrayComponentResize(REComponent, NSInteger) NS_SWIFT_NAME(Component.materialParameterBlockArray_resize(self:_:));
RE_EXTERN void REMaterialParameterBlockArrayComponentSetBlockValueAtIndex(REComponent, NSInteger, REMaterialParameterBlockValueRef) NS_SWIFT_NAME(Component.materialParameterBlockArray_setBlockValueAtIndex(self:_:_:));
RE_EXTERN void REMaterialParameterBlockArrayComponentReturnBlockValueAtIndex(REComponent, NSInteger, REMaterialParameterBlockValueRef) NS_SWIFT_NAME(Component.materialParameterBlockArray_returnBlockValueAtIndex(self:_:_:));
RE_EXTERN bool REMaterialRenderStateArrayComponentGetTriangleFillModeAtIndex(REComponent, NSInteger, MTLTriangleFillMode *) NS_SWIFT_NAME(Component.materialRenderStateArray_getTriangleFillModeAtIndex(self:_:_:));
RE_EXTERN bool REMaterialRenderStateArrayComponentGetCullModeAtIndex(REComponent, NSInteger, MTLCullMode *) NS_SWIFT_NAME(Component.materialRenderStateArray_getCullModeAtIndex(self:_:_:));
RE_EXTERN bool REMaterialRenderStateArrayComponentGetWritesDepthAtIndex(REComponent, NSInteger, bool *) NS_SWIFT_NAME(Component.materialRenderStateArray_getWritesDepthAtIndex(self:_:_:));
RE_EXTERN bool REMaterialRenderStateArrayComponentGetReadsDepthAtIndex(REComponent, NSInteger, bool *) NS_SWIFT_NAME(Component.materialRenderStateArray_getReadsDepthAtIndex(self:_:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentSetTriangleFillModeAtIndex(REComponent, NSInteger, MTLTriangleFillMode) NS_SWIFT_NAME(Component.materialRenderStateArray_setTriangleFillModeAtIndex(self:_:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentClearTriangleFillModeAtIndex(REComponent, NSInteger) NS_SWIFT_NAME(Component.materialRenderStateArray_clearTriangleFillModeAtIndex(self:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentClearCullModeAtIndex(REComponent, NSInteger) NS_SWIFT_NAME(Component.materialRenderStateArray_clearCullModeAtIndex(self:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentClearReadsDepthAtIndex(REComponent, NSInteger) NS_SWIFT_NAME(Component.materialRenderStateArray_clearReadsDepthAtIndex(self:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentSetReadsDepthAtIndex(REComponent, NSInteger, bool) NS_SWIFT_NAME(Component.materialRenderStateArray_setReadsDepthAtIndex(self:_:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentSetCullModeAtIndex(REComponent, NSInteger, MTLCullMode) NS_SWIFT_NAME(Component.materialRenderStateArray_setCullModeAtIndex(self:_:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentClearWritesDepthAtIndex(REComponent, NSInteger) NS_SWIFT_NAME(Component.materialRenderStateArray_clearWritesDepthAtIndex(self:_:));
RE_EXTERN void REMaterialRenderStateArrayComponentSetWritesDepthAtIndex(REComponent, NSInteger, bool) NS_SWIFT_NAME(Component.materialRenderStateArray_setWritesDepthAtIndex(self:_:_:));

NS_ASSUME_NONNULL_END
